/**
 * @interface CountryCode
 * @description Defines the structure for a country's dialing code information.
 * @property {string} code - The international dialing code (e.g., '+1').
 * @property {string} country - The common name of the country or territory.
 * @property {string} flag - The emoji flag representing the country.
 * @property {number} maxLength - The typical maximum length of a national phone number, excluding the country code.
 */
export interface CountryCode {
  code: string;
  country: string;
  flag: string;
  maxLength: number;
}

/**
 * @const countryCodes
 * @description An array of objects containing dialing code information for countries and territories worldwide.
 * The list is sorted alphabetically by country name.
 */
export const countryCodes: CountryCode[] = [
  { code: '+93', country: 'Afghanistan', flag: '🇦🇫', maxLength: 9 },
  { code: '+355', country: 'Albania', flag: '🇦�', maxLength: 9 },
  { code: '+213', country: 'Algeria', flag: '🇩🇿', maxLength: 9 },
  { code: '+1684', country: 'American Samoa', flag: '🇦🇸', maxLength: 7 },
  { code: '+376', country: 'Andorra', flag: '🇦🇩', maxLength: 6 },
  { code: '+244', country: 'Angola', flag: '🇦🇴', maxLength: 9 },
  { code: '+1264', country: 'Anguilla', flag: '🇦🇮', maxLength: 7 },
  { code: '+1268', country: 'Antigua & Barbuda', flag: '🇦🇬', maxLength: 7 },
  { code: '+54', country: 'Argentina', flag: '🇦🇷', maxLength: 10 },
  { code: '+374', country: 'Armenia', flag: '🇦🇲', maxLength: 8 },
  { code: '+297', country: 'Aruba', flag: '🇦🇼', maxLength: 7 },
  { code: '+61', country: 'Australia', flag: '🇦🇺', maxLength: 9 },
  { code: '+43', country: 'Austria', flag: '🇦🇹', maxLength: 13 },
  { code: '+994', country: 'Azerbaijan', flag: '🇦🇿', maxLength: 9 },
  { code: '+1242', country: 'Bahamas', flag: '🇧🇸', maxLength: 7 },
  { code: '+973', country: 'Bahrain', flag: '🇧🇭', maxLength: 8 },
  { code: '+880', country: 'Bangladesh', flag: '🇧🇩', maxLength: 10 },
  { code: '+1246', country: 'Barbados', flag: '🇧🇧', maxLength: 7 },
  { code: '+375', country: 'Belarus', flag: '🇧🇾', maxLength: 9 },
  { code: '+32', country: 'Belgium', flag: '🇧🇪', maxLength: 9 },
  { code: '+501', country: 'Belize', flag: '🇧🇿', maxLength: 7 },
  { code: '+229', country: 'Benin', flag: '🇧🇯', maxLength: 8 },
  { code: '+1441', country: 'Bermuda', flag: '🇧🇲', maxLength: 7 },
  { code: '+975', country: 'Bhutan', flag: '🇧🇹', maxLength: 8 },
  { code: '+591', country: 'Bolivia', flag: '🇧🇴', maxLength: 8 },
  { code: '+387', country: 'Bosnia & Herzegovina', flag: '🇧🇦', maxLength: 8 },
  { code: '+267', country: 'Botswana', flag: '🇧🇼', maxLength: 8 },
  { code: '+55', country: 'Brazil', flag: '🇧🇷', maxLength: 11 },
  { code: '+246', country: 'British Indian Ocean Territory', flag: '🇮🇴', maxLength: 7 },
  { code: '+1284', country: 'British Virgin Islands', flag: '🇻🇬', maxLength: 7 },
  { code: '+673', country: 'Brunei', flag: '🇧🇳', maxLength: 7 },
  { code: '+359', country: 'Bulgaria', flag: '🇧🇬', maxLength: 9 },
  { code: '+226', country: 'Burkina Faso', flag: '🇧🇫', maxLength: 8 },
  { code: '+257', country: 'Burundi', flag: '🇧🇮', maxLength: 8 },
  { code: '+855', country: 'Cambodia', flag: '🇰🇭', maxLength: 9 },
  { code: '+237', country: 'Cameroon', flag: '🇨🇲', maxLength: 9 },
  { code: '+1', country: 'Canada', flag: '🇨🇦', maxLength: 10 },
  { code: '+238', country: 'Cape Verde', flag: '🇨🇻', maxLength: 7 },
  { code: '+1345', country: 'Cayman Islands', flag: '🇰🇾', maxLength: 7 },
  { code: '+236', country: 'Central African Republic', flag: '🇨🇫', maxLength: 8 },
  { code: '+235', country: 'Chad', flag: '🇹🇩', maxLength: 8 },
  { code: '+56', country: 'Chile', flag: '🇨🇱', maxLength: 9 },
  { code: '+86', country: 'China', flag: '🇨🇳', maxLength: 11 },
  { code: '+57', country: 'Colombia', flag: '🇨🇴', maxLength: 10 },
  { code: '+269', country: 'Comoros', flag: '🇰🇲', maxLength: 7 },
  { code: '+242', country: 'Congo - Brazzaville', flag: '🇨🇬', maxLength: 9 },
  { code: '+243', country: 'Congo - Kinshasa', flag: '🇨🇩', maxLength: 9 },
  { code: '+682', country: 'Cook Islands', flag: '🇨🇰', maxLength: 5 },
  { code: '+506', country: 'Costa Rica', flag: '🇨🇷', maxLength: 8 },
  { code: '+225', country: 'Côte d’Ivoire', flag: '🇨🇮', maxLength: 8 },
  { code: '+385', country: 'Croatia', flag: '🇭🇷', maxLength: 9 },
  { code: '+53', country: 'Cuba', flag: '🇨🇺', maxLength: 8 },
  { code: '+599', country: 'Curaçao', flag: '🇨🇼', maxLength: 7 },
  { code: '+357', country: 'Cyprus', flag: '🇨🇾', maxLength: 8 },
  { code: '+420', country: 'Czechia', flag: '🇨🇿', maxLength: 9 },
  { code: '+45', country: 'Denmark', flag: '🇩🇰', maxLength: 8 },
  { code: '+253', country: 'Djibouti', flag: '🇩🇯', maxLength: 6 },
  { code: '+1767', country: 'Dominica', flag: '🇩🇲', maxLength: 7 },
  { code: '+1809', country: 'Dominican Republic', flag: '🇩🇴', maxLength: 10 },
  { code: '+593', country: 'Ecuador', flag: '🇪🇨', maxLength: 9 },
  { code: '+20', country: 'Egypt', flag: '🇪🇬', maxLength: 10 },
  { code: '+503', country: 'El Salvador', flag: '🇸🇻', maxLength: 8 },
  { code: '+240', country: 'Equatorial Guinea', flag: '🇬🇶', maxLength: 9 },
  { code: '+291', country: 'Eritrea', flag: '🇪🇷', maxLength: 7 },
  { code: '+372', country: 'Estonia', flag: '🇪🇪', maxLength: 8 },
  { code: '+268', country: 'Eswatini', flag: '🇸🇿', maxLength: 8 },
  { code: '+251', country: 'Ethiopia', flag: '🇪🇹', maxLength: 9 },
  { code: '+500', country: 'Falkland Islands', flag: '🇫🇰', maxLength: 5 },
  { code: '+298', country: 'Faroe Islands', flag: '🇫🇴', maxLength: 6 },
  { code: '+679', country: 'Fiji', flag: '🇫🇯', maxLength: 7 },
  { code: '+358', country: 'Finland', flag: '🇫🇮', maxLength: 10 },
  { code: '+33', country: 'France', flag: '🇫🇷', maxLength: 10 },
  { code: '+594', country: 'French Guiana', flag: '🇬🇫', maxLength: 9 },
  { code: '+689', country: 'French Polynesia', flag: '🇵🇫', maxLength: 6 },
  { code: '+241', country: 'Gabon', flag: '🇬🇦', maxLength: 7 },
  { code: '+220', country: 'Gambia', flag: '🇬🇲', maxLength: 7 },
  { code: '+995', country: 'Georgia', flag: '🇬🇪', maxLength: 9 },
  { code: '+49', country: 'Germany', flag: '🇩🇪', maxLength: 11 },
  { code: '+233', country: 'Ghana', flag: '🇬🇭', maxLength: 9 },
  { code: '+350', country: 'Gibraltar', flag: '🇬🇮', maxLength: 8 },
  { code: '+30', country: 'Greece', flag: '🇬🇷', maxLength: 10 },
  { code: '+299', country: 'Greenland', flag: '🇬🇱', maxLength: 6 },
  { code: '+1473', country: 'Grenada', flag: '🇬🇩', maxLength: 7 },
  { code: '+590', country: 'Guadeloupe', flag: '🇬🇵', maxLength: 9 },
  { code: '+1671', country: 'Guam', flag: '🇬🇺', maxLength: 7 },
  { code: '+502', country: 'Guatemala', flag: '🇬🇹', maxLength: 8 },
  { code: '+44', country: 'Guernsey', flag: '🇬🇬', maxLength: 10 },
  { code: '+224', country: 'Guinea', flag: '🇬🇳', maxLength: 9 },
  { code: '+245', country: 'Guinea-Bissau', flag: '🇬🇼', maxLength: 7 },
  { code: '+592', country: 'Guyana', flag: '🇬🇾', maxLength: 7 },
  { code: '+509', country: 'Haiti', flag: '🇭🇹', maxLength: 8 },
  { code: '+504', country: 'Honduras', flag: '🇭🇳', maxLength: 8 },
  { code: '+852', country: 'Hong Kong', flag: '🇭🇰', maxLength: 8 },
  { code: '+36', country: 'Hungary', flag: '🇭🇺', maxLength: 9 },
  { code: '+354', country: 'Iceland', flag: '🇮🇸', maxLength: 7 },
  { code: '+91', country: 'India', flag: '🇮🇳', maxLength: 10 },
  { code: '+62', country: 'Indonesia', flag: '🇮🇩', maxLength: 12 },
  { code: '+98', country: 'Iran', flag: '🇮🇷', maxLength: 10 },
  { code: '+964', country: 'Iraq', flag: '🇮🇶', maxLength: 10 },
  { code: '+353', country: 'Ireland', flag: '🇮🇪', maxLength: 9 },
  { code: '+44', country: 'Isle of Man', flag: '🇮🇲', maxLength: 10 },
  { code: '+972', country: 'Israel', flag: '🇮🇱', maxLength: 9 },
  { code: '+39', country: 'Italy', flag: '🇮🇹', maxLength: 10 },
  { code: '+1876', country: 'Jamaica', flag: '🇯🇲', maxLength: 7 },
  { code: '+81', country: 'Japan', flag: '🇯🇵', maxLength: 11 },
  { code: '+44', country: 'Jersey', flag: '🇯🇪', maxLength: 10 },
  { code: '+962', country: 'Jordan', flag: '🇯🇴', maxLength: 9 },
  { code: '+7', country: 'Kazakhstan', flag: '🇰🇿', maxLength: 10 },
  { code: '+254', country: 'Kenya', flag: '🇰🇪', maxLength: 9 },
  { code: '+686', country: 'Kiribati', flag: '🇰🇮', maxLength: 5 },
  { code: '+383', country: 'Kosovo', flag: '🇽🇰', maxLength: 8 },
  { code: '+965', country: 'Kuwait', flag: '🇰🇼', maxLength: 8 },
  { code: '+996', country: 'Kyrgyzstan', flag: '🇰🇬', maxLength: 9 },
  { code: '+856', country: 'Laos', flag: '🇱🇦', maxLength: 10 },
  { code: '+371', country: 'Latvia', flag: '🇱🇻', maxLength: 8 },
  { code: '+961', country: 'Lebanon', flag: '🇱🇧', maxLength: 8 },
  { code: '+266', country: 'Lesotho', flag: '🇱🇸', maxLength: 8 },
  { code: '+231', country: 'Liberia', flag: '🇱🇷', maxLength: 8 },
  { code: '+218', country: 'Libya', flag: '🇱🇾', maxLength: 10 },
  { code: '+423', country: 'Liechtenstein', flag: '🇱🇮', maxLength: 7 },
  { code: '+370', country: 'Lithuania', flag: '🇱🇹', maxLength: 8 },
  { code: '+352', country: 'Luxembourg', flag: '🇱🇺', maxLength: 9 },
  { code: '+853', country: 'Macau', flag: '🇲🇴', maxLength: 8 },
  { code: '+261', country: 'Madagascar', flag: '🇲🇬', maxLength: 9 },
  { code: '+265', country: 'Malawi', flag: '🇲🇼', maxLength: 9 },
  { code: '+60', country: 'Malaysia', flag: '🇲🇾', maxLength: 10 },
  { code: '+960', country: 'Maldives', flag: '🇲🇻', maxLength: 7 },
  { code: '+223', country: 'Mali', flag: '🇲🇱', maxLength: 8 },
  { code: '+356', country: 'Malta', flag: '🇲🇹', maxLength: 8 },
  { code: '+692', country: 'Marshall Islands', flag: '🇲🇭', maxLength: 7 },
  { code: '+596', country: 'Martinique', flag: '🇲🇶', maxLength: 9 },
  { code: '+222', country: 'Mauritania', flag: '🇲🇷', maxLength: 8 },
  { code: '+230', country: 'Mauritius', flag: '🇲🇺', maxLength: 8 },
  { code: '+262', country: 'Mayotte', flag: '🇾🇹', maxLength: 9 },
  { code: '+52', country: 'Mexico', flag: '🇲🇽', maxLength: 10 },
  { code: '+691', country: 'Micronesia', flag: '🇫🇲', maxLength: 7 },
  { code: '+373', country: 'Moldova', flag: '🇲🇩', maxLength: 8 },
  { code: '+377', country: 'Monaco', flag: '🇲🇨', maxLength: 9 },
  { code: '+976', country: 'Mongolia', flag: '🇲🇳', maxLength: 8 },
  { code: '+382', country: 'Montenegro', flag: '🇲🇪', maxLength: 8 },
  { code: '+1664', country: 'Montserrat', flag: '🇲🇸', maxLength: 7 },
  { code: '+212', country: 'Morocco', flag: '🇲🇦', maxLength: 9 },
  { code: '+258', country: 'Mozambique', flag: '🇲🇿', maxLength: 9 },
  { code: '+95', country: 'Myanmar', flag: '🇲🇲', maxLength: 9 },
  { code: '+264', country: 'Namibia', flag: '🇳🇦', maxLength: 9 },
  { code: '+674', country: 'Nauru', flag: '🇳🇷', maxLength: 7 },
  { code: '+977', country: 'Nepal', flag: '🇳🇵', maxLength: 10 },
  { code: '+31', country: 'Netherlands', flag: '🇳🇱', maxLength: 9 },
  { code: '+687', country: 'New Caledonia', flag: '🇳🇨', maxLength: 6 },
  { code: '+64', country: 'New Zealand', flag: '🇳🇿', maxLength: 9 },
  { code: '+505', country: 'Nicaragua', flag: '🇳🇮', maxLength: 8 },
  { code: '+227', country: 'Niger', flag: '🇳🇪', maxLength: 8 },
  { code: '+234', country: 'Nigeria', flag: '🇳🇬', maxLength: 10 },
  { code: '+683', country: 'Niue', flag: '🇳🇺', maxLength: 4 },
  { code: '+672', country: 'Norfolk Island', flag: '🇳🇫', maxLength: 6 },
  { code: '+850', country: 'North Korea', flag: '🇰🇵', maxLength: 10 },
  { code: '+389', country: 'North Macedonia', flag: '🇲🇰', maxLength: 8 },
  { code: '+1670', country: 'Northern Mariana Islands', flag: '🇲🇵', maxLength: 7 },
  { code: '+47', country: 'Norway', flag: '🇳🇴', maxLength: 8 },
  { code: '+968', country: 'Oman', flag: '🇴🇲', maxLength: 8 },
  { code: '+92', country: 'Pakistan', flag: '🇵🇰', maxLength: 10 },
  { code: '+680', country: 'Palau', flag: '🇵🇼', maxLength: 7 },
  { code: '+970', country: 'Palestine', flag: '🇵🇸', maxLength: 9 },
  { code: '+507', country: 'Panama', flag: '🇵🇦', maxLength: 8 },
  { code: '+675', country: 'Papua New Guinea', flag: '🇵🇬', maxLength: 8 },
  { code: '+595', country: 'Paraguay', flag: '🇵🇾', maxLength: 9 },
  { code: '+51', country: 'Peru', flag: '🇵🇪', maxLength: 9 },
  { code: '+63', country: 'Philippines', flag: '🇵🇭', maxLength: 10 },
  { code: '+48', country: 'Poland', flag: '🇵🇱', maxLength: 9 },
  { code: '+351', country: 'Portugal', flag: '🇵🇹', maxLength: 9 },
  { code: '+1', country: 'Puerto Rico', flag: '🇵🇷', maxLength: 10 },
  { code: '+974', country: 'Qatar', flag: '🇶🇦', maxLength: 8 },
  { code: '+262', country: 'Réunion', flag: '🇷🇪', maxLength: 9 },
  { code: '+40', country: 'Romania', flag: '🇷🇴', maxLength: 9 },
  { code: '+7', country: 'Russia', flag: '🇷🇺', maxLength: 10 },
  { code: '+250', country: 'Rwanda', flag: '🇷🇼', maxLength: 9 },
  { code: '+590', country: 'Saint Barthélemy', flag: '🇧🇱', maxLength: 9 },
  { code: '+290', country: 'Saint Helena', flag: '🇸🇭', maxLength: 4 },
  { code: '+1869', country: 'Saint Kitts & Nevis', flag: '🇰🇳', maxLength: 7 },
  { code: '+1758', country: 'Saint Lucia', flag: '🇱🇨', maxLength: 7 },
  { code: '+590', country: 'Saint Martin', flag: '🇲🇫', maxLength: 9 },
  { code: '+508', country: 'Saint Pierre & Miquelon', flag: '🇵🇲', maxLength: 6 },
  { code: '+1784', country: 'Saint Vincent & Grenadines', flag: '🇻🇨', maxLength: 7 },
  { code: '+685', country: 'Samoa', flag: '🇼🇸', maxLength: 7 },
  { code: '+378', country: 'San Marino', flag: '🇸🇲', maxLength: 10 },
  { code: '+239', country: 'São Tomé & Príncipe', flag: '🇸🇹', maxLength: 7 },
  { code: '+966', country: 'Saudi Arabia', flag: '🇸🇦', maxLength: 9 },
  { code: '+221', country: 'Senegal', flag: '🇸🇳', maxLength: 9 },
  { code: '+381', country: 'Serbia', flag: '🇷🇸', maxLength: 9 },
  { code: '+248', country: 'Seychelles', flag: '🇸🇨', maxLength: 7 },
  { code: '+232', country: 'Sierra Leone', flag: '🇸🇱', maxLength: 8 },
  { code: '+65', country: 'Singapore', flag: '🇸🇬', maxLength: 8 },
  { code: '+1721', country: 'Sint Maarten', flag: '🇸🇽', maxLength: 7 },
  { code: '+421', country: 'Slovakia', flag: '🇸🇰', maxLength: 9 },
  { code: '+386', country: 'Slovenia', flag: '🇸🇮', maxLength: 8 },
  { code: '+677', country: 'Solomon Islands', flag: '🇸🇧', maxLength: 7 },
  { code: '+252', country: 'Somalia', flag: '🇸🇴', maxLength: 8 },
  { code: '+27', country: 'South Africa', flag: '🇿🇦', maxLength: 9 },
  { code: '+82', country: 'South Korea', flag: '🇰🇷', maxLength: 11 },
  { code: '+211', country: 'South Sudan', flag: '🇸🇸', maxLength: 9 },
  { code: '+34', country: 'Spain', flag: '🇪🇸', maxLength: 9 },
  { code: '+94', country: 'Sri Lanka', flag: '🇱🇰', maxLength: 9 },
  { code: '+249', country: 'Sudan', flag: '🇸🇩', maxLength: 9 },
  { code: '+597', country: 'Suriname', flag: '🇸🇷', maxLength: 7 },
  { code: '+46', country: 'Sweden', flag: '🇸🇪', maxLength: 10 },
  { code: '+41', country: 'Switzerland', flag: '🇨🇭', maxLength: 9 },
  { code: '+963', country: 'Syria', flag: '🇸🇾', maxLength: 9 },
  { code: '+886', country: 'Taiwan', flag: '🇹🇼', maxLength: 9 },
  { code: '+992', country: 'Tajikistan', flag: '🇹🇯', maxLength: 9 },
  { code: '+255', country: 'Tanzania', flag: '🇹🇿', maxLength: 9 },
  { code: '+66', country: 'Thailand', flag: '🇹🇭', maxLength: 9 },
  { code: '+670', country: 'Timor-Leste', flag: '🇹🇱', maxLength: 8 },
  { code: '+228', country: 'Togo', flag: '🇹🇬', maxLength: 8 },
  { code: '+690', country: 'Tokelau', flag: '🇹🇰', maxLength: 4 },
  { code: '+676', country: 'Tonga', flag: '🇹🇴', maxLength: 5 },
  { code: '+1868', country: 'Trinidad & Tobago', flag: '🇹🇹', maxLength: 7 },
  { code: '+216', country: 'Tunisia', flag: '🇹🇳', maxLength: 8 },
  { code: '+90', country: 'Turkey', flag: '🇹🇷', maxLength: 10 },
  { code: '+993', country: 'Turkmenistan', flag: '🇹🇲', maxLength: 8 },
  { code: '+1649', country: 'Turks & Caicos Islands', flag: '🇹🇨', maxLength: 7 },
  { code: '+688', country: 'Tuvalu', flag: '🇹🇻', maxLength: 5 },
  { code: '+1340', country: 'U.S. Virgin Islands', flag: '🇻🇮', maxLength: 7 },
  { code: '+256', country: 'Uganda', flag: '🇺🇬', maxLength: 9 },
  { code: '+380', country: 'Ukraine', flag: '🇺🇦', maxLength: 9 },
  { code: '+971', country: 'United Arab Emirates', flag: '🇦🇪', maxLength: 9 },
  { code: '+44', country: 'United Kingdom', flag: '🇬🇧', maxLength: 10 },
  { code: '+1', country: 'United States', flag: '🇺🇸', maxLength: 10 },
  { code: '+598', country: 'Uruguay', flag: '🇺🇾', maxLength: 8 },
  { code: '+998', country: 'Uzbekistan', flag: '🇺🇿', maxLength: 9 },
  { code: '+678', country: 'Vanuatu', flag: '🇻🇺', maxLength: 7 },
  { code: '+379', country: 'Vatican City', flag: '🇻🇦', maxLength: 10 },
  { code: '+58', country: 'Venezuela', flag: '🇻🇪', maxLength: 10 },
  { code: '+84', country: 'Vietnam', flag: '🇻🇳', maxLength: 10 },
  { code: '+681', country: 'Wallis & Futuna', flag: '🇼🇫', maxLength: 6 },
  { code: '+967', country: 'Yemen', flag: '🇾🇪', maxLength: 9 },
  { code: '+260', country: 'Zambia', flag: '🇿🇲', maxLength: 9 },
  { code: '+263', country: 'Zimbabwe', flag: '🇿🇼', maxLength: 9 },
];