name: Build and Test

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Production
    
    defaults:
      run:
        working-directory: ./frontend
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: ./frontend/package-lock.json
        
    - name: Install dependencies
      run: npm ci
      
    - name: Lint code
      run: npm run lint
      continue-on-error: true
      
    - name: Build for web
      run: npm run build:web
      env:
        EXPO_PUBLIC_SERVER_BASE_URL: ${{ vars.EXPO_PUBLIC_SERVER_BASE_URL }}
        EXPO_PUBLIC_PROJECT_NAME: ${{ vars.EXPO_PUBLIC_PROJECT_NAME }}
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: web-build
        path: ./frontend/dist/
        retention-days: 30
